[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.api"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
healthcheckPath = "/health"
healthcheckTimeout = 60

[[services]]
name = "neng-nom-api"
environmentVariables = [
  "NODE_ENV=production",
  "PORT=3001"
]
